// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsvideoconfig = {
    "awsInputVideo": "chatvideos-dev-input-lbhpxfku",
    "awsOutputVideo": "chatvideos-dev-output-lbhpxfku.s3.us-east-1.amazonaws.com"
};

export default awsvideoconfig;