/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:b37f2451-1c69-4cc5-8b01-f9bd1e3d9f59",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_u3CNsALAv",
  aws_user_pools_web_client_id: "4ijaoatgp7re91gtq26mpskdq6",
  oauth: {},
  aws_user_files_s3_bucket:
    "clientchatapped1e5c9d9c39452c8cf1d8e5f05e6979114541-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
